name: Security Scan with Snyk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (User Service)
        working-directory: ./user-service
        run: npm install

      - name: Install Dependencies (Product Service)
        working-directory: ./product-service
        run: npm install

      - name: Run Snyk Security Scan (User Service)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          working-directory: ./user-service

      - name: Run Snyk Security Scan (Product Service)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          working-directory: ./product-service

      - name: Run Snyk Container Security Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: shabry967/user-auth-service:latest
          args: --severity-threshold=high
