name: Security Scan with Snyk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Scan User Service and push results to Snyk Dashboard
      - name: Run Snyk Security Scan (User Service)
        run: |
          cd user-service
          snyk test --severity-threshold=high
          snyk monitor  # Sends results to Snyk Dashboard

      # Scan Product Service and push results to Snyk Dashboard
      - name: Run Snyk Security Scan (Product Service)
        run: |
          cd product-service
          snyk test --severity-threshold=high
          snyk monitor  # Sends results to Snyk Dashboard

      # Scan Docker Image and push results to Snyk Dashboard
      - name: Run Snyk Container Security Scan
        run: |
          snyk container test shabry967/user-auth-service:latest
          snyk container monitor shabry967/user-auth-service:latest  # Pushes results to Snyk Dashboard
