name: CI/CD with Security Scans

on: [push]

permissions:
  contents: read

jobs:
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Dependencies (User Service)
        run: npm install
        working-directory: user-service

      - name: Install Dependencies (Product Service)
        run: npm install
        working-directory: product-service

      - name: Run Snyk Scan on User Service
        run: snyk test
        working-directory: user-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan on Product Service
        run: snyk test
        working-directory: product-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image (User Service)
        run: docker build -t user-service:latest .
        working-directory: user-service

      - name: Build Docker Image (Product Service)
        run: docker build -t product-service:latest .
        working-directory: product-service

      - name: Run Snyk Docker Scan (User Service)
        run: snyk container test user-service:latest --file=Dockerfile
        working-directory: user-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Docker Scan (Product Service)
        run: snyk container test product-service:latest --file=Dockerfile
        working-directory: product-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
