name: CI/CD with Security Scans

on: [push]

jobs:
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (User Service)
        working-directory: user-service
        run: npm install

      - name: Install Dependencies (Product Service)
        working-directory: product-service
        run: npm install

      - name: Run Snyk Scan on User Service
        working-directory: user-service
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan on Product Service
        working-directory: product-service
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image (User Service)
        working-directory: user-service
        run: docker build -t user-service:latest .

      - name: Build Docker Image (Product Service)
        working-directory: product-service
        run: docker build -t product-service:latest .

      - name: Run Snyk Docker Scan (User Service)
        run: |
          docker save user-service:latest | snyk container test --file=user-service/Dockerfile --platform=linux/amd64
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Docker Scan (Product Service)
        run: |
          docker save product-service:latest | snyk container test --file=product-service/Dockerfile --platform=linux/amd64
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
