name: CI/CD with Security Scans

on: [push]

permissions:
  contents: read

jobs:
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Dependencies (User Service)
        run: npm install
        working-directory: user-service

      - name: Install Dependencies (Product Service)
        run: npm install
        working-directory: product-service

      - name: Monitor User Service in Snyk Dashboard
        run: snyk monitor
        working-directory: user-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor Product Service in Snyk Dashboard
        run: snyk monitor
        working-directory: product-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image (User Service)
        run: docker build -t user-service:latest .
        working-directory: user-service

      - name: Build Docker Image (Product Service)
        run: docker build -t product-service:latest .
        working-directory: product-service

      - name: Monitor User Service Docker Image in Snyk Dashboard
        run: snyk container monitor user-service:latest --file=Dockerfile
        working-directory: user-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor Product Service Docker Image in Snyk Dashboard
        run: snyk container monitor product-service:latest --file=Dockerfile
        working-directory: product-service
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
